### ISSUE TITLE
No Moon Boss Spawning in Moon Dungeon

### ISSUE THREAD

**Issue by TECakaJulian** [TeamGalacticraft/Galacticraft#13] opened 2020-12-30 00:56 UTC
Im Playing Lapitos Galacticraft and in all of the dungeons i found on the moon (2) there aro no bosses. Thus i can not open the dungeon chest. Some of the Spawner Rooms and Halways are also seperated by walls. Do you need the seed and coordinate of the Moon Base?

**Comment by ROMVoid95** [comment] 2020-12-30 01:22
this needs to be reported to the owner of Laptios, they are using the 281 build. They need to revert to 280

**Comment by v1993** [comment] 2021-01-31 11:33
This is a duplicate of #3 and should be closed. As a practical solution, use build 280 (instead of 281) until update arrives.

**Closed** 2021-01-31 11:35 UTC
